# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    gym(
    clean:true,
    scheme:"FSWYNews",

    export_method:"ad-hoc",
    export_xcargs: "-allowProvisioningUpdates",
    output_directory:"./build",
 )
     pgyer(api_key: "d1b2989cde5da7909baa2e7677104a48", user_key: "fe25d4bc286baf919209843d9cb45da0", update_description: "fix something")
  end
end
